### ISSUE TITLE
Respect language dialects

### ISSUE THREAD

**Issue by akroii** [lochmueller/language_detection#34]
Hi, 
I'm using lochmueller/language-detection 4.0.0 and Typo3 11.5.30.

We have a Typo3 installation which regulates different translation on one installlation. It is not a multidomain instance.
So e.g. en_us should also be forwarded to the respective language tree.

Then we figure out that the $locale `en_us` is always reduced to `en`. This will always flatten me to en-language tree instead of en_us.

The flattening happens here:
https://github.com/lochmueller/language_detection/blob/80b7108be10495d15fc3620aa42e84c6d5bdd725/Classes/Service/LanguageService.php#L12-L20

For example we added inside of LangugaeService.php :
```php
if($country === "US") {
    return "en_US";
} else {
    return Locale::getPrimaryLanguage($locale);
}
```
... everything works.

Is there a way that you can add all 64 Language dialects in ISO 639-1?

Related [#26](https://github.com/lochmueller/language_detection/issues/26)

**Comment by lochmueller** [comment]
The result "en_US" as return argument is wrong, because the calling function add the Country after it. So the detection will end in "en_US_US". Possibly the outcome in your case is "ok", but the integration workflow is not.

Could you add the following information to this issue:
- The result of maxmind
- You Accept-Languages header
- You Site Languages configurations

Regards,
Tim

**Comment by lochmueller** [comment]
Furthermore "en_us" is not flatten to "en". The detection process normalizes all incoming information but do not drop languages. Perhaps your accepted languages are "en,en-us" or "en-us;q=0.9,en;q=1.0" or something like that? In this cases the detection handle the "en" first and not the "en-us".

**Comment by akroii** [comment]
> The result "en_US" as return argument is wrong, because the calling function add the Country after it. So the detection will end in "en_US_US". Possibly the outcome in your case is "ok", but the integration workflow is not.
> 
> Could you add the following information to this issue:
> 
> * The result of maxmind
> * You Accept-Languages header
> * You Site Languages configurations
> 
> Regards, Tim

Hi Tim,
here are my ansers:

**The result of maxmind**
https://geoip.maxmind.com/geoip/v2.1/country/77.111.246.45?pretty
```json
{
    "continent": {
        "code": "NA",
        "geoname_id": 6255149,
        "names": {
            "zh-CN": "北美洲",
            "de": "Nordamerika",
            "en": "North America",
            "es": "Norteamérica",
            "fr": "Amérique du Nord",
            "ja": "北アメリカ",
            "pt-BR": "América do Norte",
            "ru": "Северная Америка"
        }
    },
    "country": {
        "iso_code": "US",
        "geoname_id": 6252001,
        "names": {
            "es": "Estados Unidos",
            "fr": "États Unis",
            "ja": "アメリカ",
            "pt-BR": "EUA",
            "ru": "США",
            "zh-CN": "美国",
            "de": "Vereinigte Staaten",
            "en": "United States"
        }
    },
    "maxmind": {
        "queries_remaining": 471876
    },
    "registered_country": {
        "iso_code": "NO",
        "geoname_id": 3144096,
        "names": {
            "de": "Norwegen",
            "en": "Norway",
            "es": "Noruega",
            "fr": "Norvège",
            "ja": "ノルウェー王国",
            "pt-BR": "Noruega",
            "ru": "Норвегия",
            "zh-CN": "挪威"
        }
    },
    "traits": {
        "ip_address": "77.111.246.45",
        "network": "77.111.246.0/24"
    }
}
```
**Your Accept-Languages header:**
en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7

**You Site Languages configurations**
```yaml
addIpLocationToBrowserLanguage: before
allowAllPaths: false
base: /
disableRedirectWithBackendSession: false
enableLanguageDetection: true
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=348'
  -
    errorCode: 410
    errorHandler: Page
    errorContentSource: 't3://page?uid=349'
  -
    errorCode: 403
    errorHandler: Page
    errorContentSource: 't3://page?uid=351'
  -
    errorCode: 401
    errorHandler: Page
    errorContentSource: 't3://page?uid=350'
fallbackDetectionLanguage: 1
flux_content_types: ''
flux_page_templates: ''
forwardRedirectParameters: ''
languageDetectionMaxMindAccountId: 'XXXXXX'
languageDetectionMaxMindDatabasePath: ''
languageDetectionMaxMindLicenseKey: XXXXXXX
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
    languageId: 0
    excludeFromLanguageDetection: false
    deeplTargetLanguage: ''
  -
    title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: English
    hreflang: en
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: gb
    excludeFromLanguageDetection: false
    languageId: 1
    deeplTargetLanguage: EN-GB
  -
    title: ελληνικά
    enabled: true
    base: /el/
    deeplTargetLanguage: EL
    typo3Language: default
    locale: el_GR
    iso-639-1: el
    websiteTitle: ''
    navigationTitle: ελληνικά
    hreflang: el_GR
    direction: ltr
    fallbackType: free
    fallbacks: ''
    flag: gr
    excludeFromLanguageDetection: false
    languageId: 2
  -
    title: Français
    enabled: true
    base: /fr/
    deeplTargetLanguage: FR
    typo3Language: fr
    locale: fr_FR
    iso-639-1: fr
    websiteTitle: ''
    navigationTitle: Français
    hreflang: fr
    direction: ''
    fallbackType: free
    fallbacks: ''
    flag: fr
    excludeFromLanguageDetection: false
    languageId: 3
  -
    title: Italiano
    enabled: true
    base: /it/
    deeplTargetLanguage: IT
    typo3Language: it
    locale: it_IT
    iso-639-1: it
    websiteTitle: ''
    navigationTitle: Italiano
    hreflang: it
    direction: ''
    fallbackType: free
    fallbacks: ''
    flag: it
    excludeFromLanguageDetection: false
    languageId: 4
  -
    title: Nederlands
    enabled: true
    base: /nl/
    deeplTargetLanguage: NL
    typo3Language: nl
    locale: nl
    iso-639-1: nl
    websiteTitle: ''
    navigationTitle: Nederlands
    hreflang: nl
    direction: ltr
    fallbackType: free
    fallbacks: ''
    flag: nl
    excludeFromLanguageDetection: false
    languageId: 5
  -
    title: Polski
    enabled: true
    base: /pl/
    deeplTargetLanguage: PL
    typo3Language: pl
    locale: pl_PL
    iso-639-1: pl
    websiteTitle: ''
    navigationTitle: Polski
    hreflang: pl
    direction: ltr
    fallbackType: free
    fallbacks: ''
    flag: pl
    excludeFromLanguageDetection: false
    languageId: 6
  -
    title: Čeština
    enabled: true
    base: /cz
    deeplTargetLanguage: CS
    typo3Language: default
    locale: cz
    iso-639-1: cs
    websiteTitle: ''
    navigationTitle: Čeština
    hreflang: cz
    direction: ''
    fallbackType: free
    fallbacks: ''
    flag: cz
    excludeFromLanguageDetection: false
    languageId: 7
  -
    title: Español
    enabled: true
    base: /es
    deeplTargetLanguage: ES
    typo3Language: es
    locale: es
    iso-639-1: es
    websiteTitle: ''
    navigationTitle: Español
    hreflang: es
    direction: ltr
    fallbackType: free
    fallbacks: ''
    flag: es
    excludeFromLanguageDetection: false
    languageId: 8
  -
    title: 'English (US)'
    enabled: true
    base: /us
    deeplTargetLanguage: ''
    typo3Language: default
    locale: en_US
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: us
    excludeFromLanguageDetection: false
    languageId: 9
redirectHttpStatusCode: 302
rootPageId: 1
websiteTitle: ''
```
We have a main root. In this root there are 10 languages currently
<img width="477" alt="image" src="https://github.com/lochmueller/language_detection/assets/8830861/fa8ef250-1d31-4cff-b4e4-010a04952999">
But the US lang is a redirect to another website for us countries.
<img width="268" alt="image" src="https://github.com/lochmueller/language_detection/assets/8830861/8e3b7bea-b179-4f81-9304-9c8f1b5f8018">
